on: workflow_dispatch
name: 🚀 Deploy WordPress Theme (Dev)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Tailwind Style
      run: |
        cd ./app/wp-content/themes/akiralyhalott
        npm install
        npm run tailwind
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: www131.your-server.de
        username: akiralh_1
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./app/wp-content/themes/akiralyhalott/
        server-dir: /wp-content/themes/akiralyhalott/
        protocol: ftps
        port: 21
